trigger:
  - main

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: patch
    value: 0
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1

name: $(major).$(minor).$(patch)-$(Rev:r)

stages:
  - stage: test
    displayName: Test
    jobs:
      - job: dotnetTest
        displayName: dotnet test
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK 5.0'
            inputs:
              packageType: sdk
              version: 5.0.x
          - task: DotNetCoreCLI@2
            displayName: dotnet test
            inputs:
              command: test
  - stage: Deploy
    displayName: Deploy
    dependsOn: dotnetTest
    condition:
      not(eq(variables['build.reason'], 'PullRequest'))
    jobs:
      - job: pushImage
        displayName: Push Image to Registry
        inputs:
          command: buildAndPush
          containerRegistry: SteeltoeContainerRegistry
          repository: net-core-tool-service
          tags: |
            $(Build.BuildId)
            latest
