#@ load("@ytt:data", "data")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
spec:
  selector:
    matchLabels:
      app: #@ data.values.name
  template:
    metadata:
      labels:
        app: #@ data.values.name
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: #@ data.values.name
        image: steeltoe.azurecr.io/net-core-tool-service
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.name
spec:
  ports:
  - port: #@ data.values.port
  selector:
    app: #@ data.values.name
