---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-core-tool-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-core-tool-service
  template:
    metadata:
      labels:
        app: net-core-tool-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: net-core-tool-service
        image: steeltoe.azurecr.io/net-core-tool-service
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: net-core-tool-service
spec:
  ports:
  - port: 80
  selector:
    app: net-core-tool-service
